# Local example secrets.toml (TOML format). Replace placeholders with real values.
# Do NOT commit real secrets to Git. Keep this file local and add .streamlit/secrets.toml to .gitignore.

# Simple keys (Streamlit Cloud UI uses form fields; this TOML is for local .streamlit/secrets.toml)
NOAA_TOKEN = "REPLACE_WITH_YOUR_NOAA_TOKEN"
EIA_API_KEY = "REPLACE_WITH_YOUR_EIA_API_KEY"
AUTO_RUN_HISTORICAL = true

# Optional: provide a full config object (example). The app will accept either the simple keys above
# or a full `config` structure. Use one approach, not both.
[config.noaa]
token = "REPLACE_WITH_YOUR_NOAA_TOKEN"
base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"

[config.eia]
api_key = "REPLACE_WITH_YOUR_EIA_API_KEY"
base_url = "https://api.eia.gov/v2/electricity/rto/region-data/data/"

[config.paths]
raw_data = "data/raw/"
processed_data = "data/processed/"
log_file = "logs/pipeline.log"

# Example city block (add one or more [[config.cities]] sections)
[[config.cities]]
name = "New York"
state = "New York"
noaa_station_id = "GHCND:USW00094728"
eia_region_code = "NYIS"
lat = 40.7128
lon = -74.0060

[config.data_quality]
  [config.data_quality.temp_outlier_fahrenheit]
  max = 130
  min = -50
